name: oimo_physics
description: A Flutter plugin designed for three_dart and three_dart_jsm to allow users to add a simple physics engine to their 3D  project.
version: 0.0.3
homepage: https://github.com/Knightro63/oimo_physics

environment:
  sdk: ">=2.18.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
